version: '3.8'

x-field-client-base: &field-client-base
  image: field_client
  build: .
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
  restart: always
  depends_on:
    - redis

services:
  redis:
    image: valkey/valkey:8-alpine
    volumes:
      - ./redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    command: valkey-server --appendonly yes

  consumer_counter:
    <<: *field-client-base
    command:
      - python
      - field/consumers/counter.py

  client_field:
    <<: *field-client-base
    command:
      - python
      - field/client.py
      - field

  client_banned:
    <<: *field-client-base
    command:
      - python
      - field/client.py
      - banned

  client_banana:
    <<: *field-client-base
    command:
      - python
      - field/client.py
      - banana

  client_whatisfield:
    <<: *field-client-base
    command:
      - python
      - field/client.py
      - whatisfield
