[project]
name = "field"
version = "0.1.0"
description = "reddit field stuff"
requires-python = ">=3.10"
dependencies = [
    "websockets",
    "gql[all]",
    "redis",
    "hiredis",
    "requests",
    "lru-dict"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit"
]
