"""is backfill for partition update

Revision ID: 8b9e0f297a4d
Revises: bb20be1b9c8d
Create Date: 2025-04-03 03:18:57.716534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b9e0f297a4d"
down_revision: Union[str, None] = "bb20be1b9c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partition_updates",
        sa.Column(
            "is_backfill", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partition_updates", "is_backfill")
    # ### end Alembic commands ###
