"""initial

Revision ID: a04738c063ad
Revises:
Create Date: 2025-04-02 15:06:09.900553

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a04738c063ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
