"""field message kind

Revision ID: a42e5a182dea
Revises: f943c2af6bbf
Create Date: 2025-04-02 15:47:50.219933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a42e5a182dea"
down_revision: Union[str, None] = "f943c2af6bbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field_messages", sa.Column("kind", sa.String()))
    op.execute("UPDATE field_messages SET kind = 'unknown'")
    op.alter_column("field_messages", "kind", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_messages", "kind")
    # ### end Alembic commands ###
