"""field partition update

Revision ID: b4d6b499c149
Revises: a42e5a182dea
Create Date: 2025-04-02 16:21:16.054681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4d6b499c149"
down_revision: Union[str, None] = "a42e5a182dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partition_updates",
        sa.Column("partition_x", sa.Integer(), nullable=False),
        sa.Column("partition_y", sa.Integer(), nullable=False),
        sa.Column("subredditId", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("challengeNumber", sa.Integer(), nullable=False),
        sa.Column("sequenceNumber", sa.Integer(), nullable=False),
        sa.Column("noChange", sa.Boolean(), nullable=False),
        sa.Column("pathPrefix", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint(
            "partition_x",
            "partition_y",
            "subredditId",
            "kind",
            "challengeNumber",
            "sequenceNumber",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partition_updates")
    # ### end Alembic commands ###
