"""has file for updates

Revision ID: bb20be1b9c8d
Revises: b4d6b499c149
Create Date: 2025-04-03 00:55:33.645808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb20be1b9c8d"
down_revision: Union[str, None] = "b4d6b499c149"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partition_updates",
        sa.Column(
            "has_file", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partition_updates", "has_file")
    # ### end Alembic commands ###
