"""field message jsonb

Revision ID: f943c2af6bbf
Revises: fb69987da9c6
Create Date: 2025-04-02 15:38:02.142607

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f943c2af6bbf"
down_revision: Union[str, None] = "fb69987da9c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE field_messages
        ALTER COLUMN backend_message TYPE jsonb
        USING backend_message::jsonb;""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # no goin back
