"""reddit unique id

Revision ID: fb69987da9c6
Revises: a04738c063ad
Create Date: 2025-04-02 15:24:42.457086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb69987da9c6"
down_revision: Union[str, None] = "a04738c063ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field_messages", sa.Column("reddit_id", sa.String(), nullable=False))
    op.create_unique_constraint(None, "field_messages", ["reddit_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "field_messages", type_="unique")
    op.drop_column("field_messages", "reddit_id")
    # ### end Alembic commands ###
